# 服务器关配置
server:
  port: 8083
  servlet:
    context-path: /Manager
  tomcat:
      # tomcat的uri编码  解决get请求中文乱码
      uri-encoding: UTF-8
      # 配置tomcat最大的线程数
      max-threads: 800
      # 配置tomcat初始化线程数
      min-spare-threads: 30
# 日志信息配置
logging:
  level:
    com.chinasofti: debug
    org.springframework: warn
# spring 配置
spring:
  application:
    name: shop-usermanager
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #配置加载其它配置文件
  profiles:
    active: druid,mybatis,dubbo
 #配置文件上传
servlet:
    multipart:
      max-file-size: 5M
      max-request-size: 50M
