dubbo:
  application:
    name: "shop-manager-service"
  #指定注册中心的协议和地址
  registry:
    protocol: "zookeeper"
#    address: "192.168.76.130:2181"
    address: "192.168.5.121:2181"
  protocol:
    name: "dubbo"
    port: 20880